//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement_proj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DoctorWorkloadStats
    {
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> UpcomingAppointments { get; set; }
        public Nullable<int> CompletedAppointments { get; set; }
        public Nullable<int> TotalAppointments { get; set; }
    }
}
